version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: iscope-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    build:
      context: ./web
    container_name: iscope-web
    ports:
      - "80:80"

