version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: iscope-postgres
    environment:
      POSTGRES_USER: iscope360
      POSTGRES_PASSWORD: zr;;2hY56r-£:V8_7Y=m
      POSTGRES_DB: iscope360
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: iscope-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio
    container_name: iscope-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: iscope360
      MINIO_ROOT_PASSWORD: ekN\yZ-n6303T0tgao{@
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
