-- Tabela task_step_results não existe nas migrações do V1 (provavelmente uma feature abortada a favor da coluna JSONB).
-- ALTER TABLE task_step_results 
-- ADD CONSTRAINT task_step_results_task_id_step_id_unique 
-- UNIQUE (task_id, step_id);